In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd 
data1=pd.read_csv("data.csv")
data1

sno  Temperature  Pressure
0    1            0    0.0002
1    2           20    0.0012
2    3           40    0.0060
3    4           60    0.0300
4    5           80    0.0900
5    6          100    0.2700

In [15]:
X = data1.iloc[:, 1:2].values 
X

array([[  0],
       [ 20],
       [ 40],
       [ 60],
       [ 80],
       [100]])

In [6]:
X = data1.iloc[:, 1].values
X

array([  0,  20,  40,  60,  80, 100])

In [11]:
X = data1.iloc[:, 0:2].values
X

array([[  1,   0],
       [  2,  20],
       [  3,  40],
       [  4,  60],
       [  5,  80],
       [  6, 100]])

In [17]:
type(data1.iloc[:, 1:2])

pandas.core.frame.DataFrame

In [28]:
y = data1.iloc[:,2].values
y

array([  2.00000000e-04,   1.20000000e-03,   6.00000000e-03,
         3.00000000e-02,   9.00000000e-02,   2.70000000e-01])

In [ ]:
from sklearn.linear_model import LinearRegression 
lin = LinearRegression() 
lin.fit(X, y) 


In [ ]:
# Fitting Polynomial Regression to the dataset 
from sklearn.preprocessing import PolynomialFeatures 

poly = PolynomialFeatures(degree = 4) 
X_poly = poly.fit_transform(X) 

poly.fit(X_poly, y) 
lin2 = LinearRegression() 
lin2.fit(X_poly, y) 


Temperature
0            0
1           20
2           40
3           60
4           80
5          100

ValueError: Found input variables with inconsistent numbers of samples: [1, 6]